# Generated by Django 3.0.3 on 2020-02-20 07:17

import course.helpers
import course.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CourseId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='CourseId')),
            ],
            options={
                'verbose_name': 'CourseId',
                'verbose_name_plural': "CourseId's",
            },
        ),
        migrations.CreateModel(
            name='scormcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='a user friendly url', max_length=250, null=True, verbose_name='user friendly url')),
                ('scorm_type', models.CharField(blank=True, choices=[('SCORM 1.2', 'SCORM 1.2'), ('SCORM 2004', 'SCORM 2004')], max_length=40, null=True)),
                ('package', models.FileField(upload_to=course.helpers.RandomFileName('course'), verbose_name='SCORM file')),
                ('courseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.CourseId', verbose_name='CourseId')),
            ],
            bases=(course.models.ExtractPackageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Course Name')),
                ('image', models.ImageField(upload_to=course.helpers.RandomFileName('course_image'), verbose_name='Course Thumbnail')),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('description', models.TextField(blank=True, help_text='a description of the Course', verbose_name='Course Description')),
                ('course_requirements', models.TextField(blank=True, help_text='Course requirements.', verbose_name='Course requirements')),
                ('target_audience', models.TextField(blank=True, help_text='Who need this course?', verbose_name='Target Audience')),
                ('category', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Category', verbose_name='Category')),
                ('courseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.CourseId', verbose_name='CourseId')),
            ],
            options={
                'verbose_name': 'CourseDetails',
                'verbose_name_plural': 'CourseDetails',
            },
        ),
    ]
