# Generated by Django 3.0.3 on 2020-02-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='duplicate_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='original_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
