# Generated by Django 3.0.5 on 2020-08-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200228_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Course Name'),
        ),
    ]
