# Generated by Django 3.0.5 on 2020-08-28 12:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0003_auto_20200817_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sent Date')),
                ('student_name', models.CharField(max_length=60, verbose_name='Student name')),
                ('student_id', models.CharField(max_length=60, verbose_name='Student id')),
                ('message', models.TextField(blank=True, verbose_name='Message contents')),
                ('courseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.CourseId', verbose_name='CourseId')),
            ],
        ),
    ]
