# Generated by Django 3.0.5 on 2020-08-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='courseid',
            field=models.CharField(default=1, max_length=60, verbose_name='CourseId'),
            preserve_default=False,
        ),
    ]
