# Generated by Django 3.0.5 on 2020-08-31 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200817_1513'),
        ('discuss', '0002_auto_20200828_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='courseid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.CourseId', verbose_name='CourseId'),
        ),
    ]
