# Generated by Django 3.0.3 on 2020-02-20 07:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=70)),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Subject')),
                ('messages', models.TextField(verbose_name='Messages')),
                ('sent_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 20, 7, 17, 13, 753530, tzinfo=utc), null=True, verbose_name='Sent date')),
            ],
        ),
    ]
