# Generated by Django 3.0.3 on 2020-02-20 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sent_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 20, 7, 19, 41, 388739, tzinfo=utc), null=True, verbose_name='Sent date'),
        ),
    ]
