# Generated by Django 3.0.3 on 2020-02-28 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20200220_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sent_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sent date'),
        ),
    ]
