# Generated by Django 3.0.3 on 2020-02-20 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=40, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=40, null=True)),
                ('education', models.CharField(blank=True, choices=[('doctorate', 'Doctorate'), ('master', "Master's or professional degree"), ('bachelor', "Bachelor's degree"), ('assosiate', 'Assosiate degree'), ('noformal', 'No formal education'), ('other', 'Other education')], max_length=40, null=True)),
                ('about', models.CharField(blank=True, max_length=1200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorm_type', models.CharField(blank=True, max_length=60, null=True, verbose_name='Scorm type')),
                ('student_id', models.CharField(max_length=60, verbose_name='Student id')),
                ('student_name', models.CharField(max_length=60, verbose_name='Student name')),
                ('lesson_location', models.CharField(blank=True, max_length=60, null=True, verbose_name='Lesson location')),
                ('max_score', models.CharField(blank=True, max_length=60, null=True, verbose_name='Max score')),
                ('raw_score', models.CharField(blank=True, max_length=60, null=True, verbose_name='Raw score')),
                ('min_score', models.CharField(blank=True, max_length=60, null=True, verbose_name='Min score')),
                ('lesson_mode', models.CharField(blank=True, max_length=60, null=True, verbose_name='Lesson mode')),
                ('lesson_status', models.CharField(blank=True, max_length=60, null=True, verbose_name='Status')),
                ('entry', models.CharField(blank=True, max_length=60, null=True, verbose_name='Entry')),
                ('credit', models.CharField(blank=True, max_length=60, null=True, verbose_name='Credit')),
                ('session_time', models.CharField(blank=True, max_length=60, null=True, verbose_name='Session time')),
                ('total_time', models.CharField(blank=True, max_length=60, null=True, verbose_name='Total time')),
                ('exit', models.CharField(blank=True, max_length=60, null=True, verbose_name='Exit')),
                ('suspend_data', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Suspend Data')),
                ('scaled_passing_score', models.CharField(blank=True, max_length=60, null=True, verbose_name='Scaled Passing Score')),
                ('success_status', models.CharField(blank=True, max_length=60, null=True, verbose_name='Success Status')),
                ('progress_measure', models.CharField(blank=True, max_length=60, null=True, verbose_name='Progress Measure')),
                ('courseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.CourseId', verbose_name='CourseId')),
            ],
        ),
    ]
