# Generated by Django 3.0.3 on 2020-02-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_enrollment_enrolled_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='Enrolled_date',
            new_name='enrolled_date',
        ),
    ]
