# Generated by Django 3.0.5 on 2020-04-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200228_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enrolled Date'),
        ),
    ]
