# Generated by Django 3.0.5 on 2020-08-17 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200817_1513'),
        ('user', '0004_auto_20200402_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='category',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Course Name'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Image Url'),
        ),
    ]
