# Generated by Django 3.0.5 on 2020-08-18 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200817_1513'),
        ('user', '0005_auto_20200817_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='image',
            field=models.ImageField(default=1, upload_to='course_image/', verbose_name='Course Thumbnail'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=60, verbose_name='Student name')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sent Date')),
                ('courseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.CourseId', verbose_name='CourseId')),
            ],
        ),
    ]
